apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deribit-subscription-secrets
  namespace: nq
spec:
  encryptedData: {}
  template:
    metadata:
      name: deribit-subscription-secrets
      namespace: nq
    type: Opaque
