---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deribit-subscription-secrets
  namespace: nq
spec:
  encryptedData:
    DERIBIT_CLIENT_ID: AgCgBh1RyLb2laSrexp4ryF7TNXzsJas0K2XXGM7iRL1KTbA0G1hvq/AImdVSAxpBlkVb2Ty5hvWujJyTrbRTtPumPzebJvYm0KFbDWbnOyyh5Nrhzkx6lIu2iUTOS+jeXAheYJYTovBSJjk8n/o13YnIY7z0LAePPgTEY5k3t7Ll4JZm2Np7LtXZHA4HH0sKMlj5F2Zk2oCwDEA1bs2QJ3+hdzWW5uU9cB8k/CmNXy/PxzWmPZnoErty5rmpqxEFz/KzXrGMgZdrEpMRzNrLNBBPknUIM6ah1tPM12laJX6COmBOlfmHXj+n8MxaNa3TC8wwKRbY348+tvCFKUIIqR2zwimBNuLUF01vaD09OTMlzuU+WnNKRLt59+JhTNNKZbQ9Y7r5M2bxN72w21w2XtY9raSG+q/jLZXeQn4uQS3MeKovrzSAHz0ta9YxORYd0K30icoWHBKC/EPHxQPF9H8u2th4BHGiCg1oQjy3tbHiWe2wwBQpPwov3KP1ta8pXKz9wD2VlDb79VfbrFTO1Jd/xFEcBbJLP2DMC4WQxK1qNfXLQKhBt1VtJcrYC5f3vDU7bYqG9BEFnpTBatnHGkKi1IFWwCIdJLPMhSGN5We+bcq5eDLmcncf+qW0HyFQDIQ+QOGQdBH1WYfDEgylarEWOs+O2q7DKR9EmC3KiYzuNdDE205ufHU1sJDyJYvfSxGiSu+p6eNUw==
    DERIBIT_CLIENT_SECRET: AgAxPzJb4ufbZ2qgTszTEdVxoSCtaqol4I6vV33aEZLayohQZ1SMriWqdOa3s0jJMVhqhBYsdUvRhHZ2WFsEGmaF38l7On3MxZfbunQLZNhE+rryyJ1lUzvf1maNCXTSqp5cvL+NtGb4nAcJMR3+w6XbvDsBdnkLOQG1yg+APAUyfrx/KaPX73tdd+l5H0VUeiTcmXCTxm8KLNF2SjOywQUBjTdfOgNyB0vk7xJn2TAQKnsmxY1NK1DsYSLYc2A1scMd6gGn6fS1m3OOmbYJg1CLCmwWne5WJEqKRZoQiDnriMODRIFLJhFV04z5BN6sEw57RB+YxqChArUkEbK2ibui8YBHX0g/Thl5F2xq6p81IMu6ewJqReLniz/Gyz0w9tabfstYY0s+BDv3W5K1c7rkoGoTF7oXVdrQSF/RKvxUQ8dAbmzVKAZC4VSZES2Yrlk/5alrE9f/wlpa/BPePlq9xBayfjQWoGM0jcf4zYqIY+9hKQoEL9x9GVZUoiYXddzTgOTJtEoS0GjvBJ3gpX0kipsy3WjVVUev9shdkzOzqMVkWxabehjtbUNq1v9i5y05ePQnw1QAajEbwcZpZNXXxbLDT0ofTFZT16YicbzzPUJvQb7cw/uUAaaFJlq8Y8ZkRNBjn7UqwjGD1bo3KmAFN9FntKPVu6LsmPzfwK0vlXDZX0BsTxwGgNKqxjSxWGGFuiOfuVT4szXA0Nx/L2IZcsOS1J7GYINfQ7zyU9uducDGMhU5nDVEws31
  template:
    metadata:
      name: deribit-subscription-secrets
      namespace: nq
    type: Opaque
