apiVersion: apps/v1
kind: Deployment
metadata:
  name: deribit-subscription
  labels:
    app: deribit-subscription
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deribit-subscription
  template:
    metadata:
      labels:
        app: deribit-subscription
    spec:
      containers:
        - name: deribit-subscription
          image: ghcr.io/bestnathan/nq-rs/deribit-subscription:latest
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: info
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: ghcr-bestnathan
      nodeSelector:
        kubernetes.io/arch: amd64
