apiVersion: apps/v1
kind: Deployment
metadata:
  name: deribit-subscription
  labels:
    app: deribit-subscription
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deribit-subscription
  template:
    metadata:
      labels:
        app: deribit-subscription
    spec:
      containers:
        - name: deribit-subscription
          image: ghcr.io/bestnathan/nq-rs/deribit-subscription:sha-39e19f3
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: info
            - name: ALL_PROXY
              value: http://192.168.2.98:8890
            - name: HTTPS_PROXY
              value: http://192.168.2.98:8890
            - name: DERIBIT_SUBSCRIPTION_CHANNELS_FILE
              value: /etc/deribit-subscription/channels.txt
          volumeMounts:
            - name: channels
              mountPath: /etc/deribit-subscription
              readOnly: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: channels
          configMap:
            name: deribit-subscription-channels
      imagePullSecrets:
        - name: ghcr-bestnathan
      nodeSelector:
        kubernetes.io/arch: amd64
