[package]
edition = "2021"
name = "application"
version = "0.1.0"

[dependencies]
anyhow = {workspace = true}
async-trait = {workspace = true}
futures-util = {workspace = true}
tokio = {workspace = true}
tokio-util = {workspace = true}
tracing = {workspace = true}
tracing-subscriber = {workspace = true}
