[package]
edition = "2024"
name = "deribit-option-monitor"
version = "0.1.0"

[dependencies]
anyhow = {workspace = true}
async-trait = {workspace = true}
flume = {workspace = true}
futures-util = {workspace = true}
nq-app = {workspace = true}
nq-deribit = {workspace = true}
nq-env = {workspace = true}
nq-mqtt = {workspace = true}
reqwest = {version = "0.12", default-features = false, features = ["rustls-tls", "json"]}
rumqttc = "0.24.0"
serde = {workspace = true}
serde_json = {workspace = true}
tokio = {workspace = true}
tokio-util = {workspace = true}
tracing = {workspace = true}
tracing-subscriber = {workspace = true}
