apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nq-rs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/BestNathan/nq-rs.git
    targetRevision: feat/deribit
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: nq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
