---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-bestnathan
  namespace: nq
spec:
  encryptedData:
    .dockerconfigjson: AgAdBodtQcbokZMl4LXVLH4Lg3cuWhTxEBfxmNaqvdrQa3EF3DTcynU29Ihi+fFnb1MHWgFsfLVJnmXHOG2PJkiYqP6BJT6Z9u5flPRfDGOGHbkbd7+/RVKLRguzRklzQHVTzGJb6ZF9qzffHojGEGg2Htdx9whPmMyM7KFnsAKTXCPwJ5/PjEPwQMYTKB65k1tnF8ADDd560vNHoYjs3HLQXM+/ahnmvnCaJKNeE0lZcSZgFazsfdJzVNqHwwqMUEAIKKE6cpbIc9he4Bqax7CCe/gnU7o0k6cz88Qz6OhA+2JsQA53y+zt8/CFmVPZM3WWv3JQz/sK/j2XOb5godu32ttg3jDOBu0ANtAZ0MqC1mCznSZKoIU9u0bUIxLe4cAejjVk2/kdsliqbku7MGO/u6as0sBHwEiX+LjfXuRfoJcGXl2WrSuWvxhXt5XsadMPaeIkJlIP278mSlYBLU1WFqlh7kgQKJYe2qFOiKICHVZf6ajt8aOgSSw1arc+jfK+EbUnoX/1GW3/SWvUTqpZvJwZXomEPEOGWqQn2+94JWGzyDDcLed+o6dkeGAxChXDcvZq/RpLqwj3YIFdke6A5i6FLaSWiaVTX0vJA4bk8tABvTe6nE0s6ghy4A1Rnc4knBoEUyg0XDbCrTFJjBNGYiF979edrd8Jt2xwc8bzYs3cB1153MQBlb7/4SFpz1ohhW5uoajPbbRPNSwkB2pvISHadAwbqMdjH9aS1dtgPjMDeAbd9ki1GOnbJ6D3UgYrV5i/gRN03kBYX+pQ/V3/pDST304EeomysEuDqSz4U8gO5gKUbYe/bymrK2NTa8oTDUj1nDOt/n0yscgHGtapy6enIMGscoglUwrOyI1DTavwaorqqO74A8eOW2rzAFk48a3kkqbOYzjqpYJuB3q33/+i8aZZzH5/DTggEbMPofRKnw==
  template:
    metadata:
      name: ghcr-bestnathan
      namespace: nq
    type: kubernetes.io/dockerconfigjson
