[package]
edition = "2021"
name = "deribit-subscription"
version = "0.1.0"

[dependencies]
anyhow = "1.0.96"
flume = "0.11.1"
futures-util = "0.3.31"
rand = "0.9.0"
reqwest = {version = "0.12", features = ["json"]}
reqwest-websocket = "0.4.4"
rumqttc = "0.24.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.137"
tokio = {version = "*", features = ["full"]}
tokio-tungstenite = "0.26.1"
tokio-util = {version = "0.7.13", features = ["rt"]}
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
