---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: option-monitor-secrets
  namespace: nq
spec:
  encryptedData:
    DERIBIT_CLIENT_ID: AgBgHywIJElUkob29gVJxH7CZbujzTnLVyq/EENxUM0yAvaSHTVUdertBr89ftEG10JfXvcF31JACpe9diPNFYO+SYRne0QrRj3JKhXtmA+3KQ+MwQk1OkqHRDKkhhcWHnKww55g5U6n9p0BAuL6GgqdJUINppog608ZKkquICbjPPfdPOG8+GBuhbGHcJIDsuxIszzeXOS4tK/ZdlZ96bpRfSKjxhs1YUkQQff1kWizQ2jCz1f/BEm6Oen2qww1SoXM/HTqbP1O24MtY+/Prg5fKpy18WuX2TBhBNDg5wpAXevPvqlI6t1mK0YbGnexjToW8fRdsH37/EePoylv6xEUydXHcbs7l/6k7lUdXnth2eGa6WpS2Rh7wl8Rdns6iBE9ytg4wCwIwQr9OSEuPihgfREl1SiJAtOGf4ukV84LdCzFZ0cutT0y6tR8RlG6KMyaO3C+CxKUuhJFst6Gi2m0AmzjwidefCO5VJA+AdYC0t7SLe0J6bqJUg7Gfriw51kbGuom53zehHQEiedCaZALH0VFtFsZJgMslO+/qrUDUEBXBAsUYh+4DBnhvyLEo4315yUzlWJaw3kn81OM8+uiIly+I55vzIBMlsELFY23OEi65kPbMZSBeuiWCLW4FKasXEOBFQcq8QyNqb+k5U058MEh7josUHUjatWIqPoxTqrlX9oUf7ttwP/pLzMOjoFFq3o/nGWFbA==
    DERIBIT_CLIENT_SECRET: AgBiNzp1UWxTxIXVqBS7eXdz5MQtqlFhnar9nbGDrkKWPB4PYUteNqJ/KK//1/SjzMmaOoKNHY3deNn+H+ZH9wgQ0c1aqATZh8TJpAIHb0ZOjQJKEkaGTBkTPg0iz9KAD+P6V5ZGmOH3yf7bm+Gs8a5Ra2DlaVBgO9aG8ZJWBBjjYxKuCVQeTkUDWkPyk8kX3oatYj8ZLKNOcHiT4QOOURgE2CVDFs9fDoWpilcTEnKeuUZzE4of6P57FKalp0Rj2x3AWAwwEuV2uv0iSQSLXPC/QD8NssXRvMlyYoXm76TQWIB0t70VEtS0r0AEBFj2J1oQpr6UZe3SV3oQpPFfo8C5tsYl6NzAyBsrntsiSK6RN5DWoC4JDT7EzGJ3VplnyHescDE1LVI0cOzFVOZit8hcmqpZ8toq1vZjz1ibU4doGMrjtZfQzIBJUELI7eQhVksaQQV4CuhuDGPy9RHXgBlfI0EO2WmT8vCZa48/Fn0qP43L2pz+pn4aUqQN2azUQo5kpP4upzuzvLLT38GurQ46x/LF55m62nHhO81BJcKPH3IXSqU9A2ynKpFrOcfrvjtRRIdSB4dumERa0RL1raRt88lGsBHgJfAX7bsm3WhxuNih9y5s0eUJqwNlmeToyrVi8+Xsl4mQeWxjAYok83V0/+SCQa9kXwEhUyFgZDtxZZBsUBaoJCCoy40igVR7zU1Gnm+sLBo6Er3ZfxGqVfLN1p1LDN15U+3gdcS5pJoEf7eKMQnrNq5N58NS
  template:
    metadata:
      name: option-monitor-secrets
      namespace: nq
    type: Opaque
