apiVersion: apps/v1
kind: Deployment
metadata:
  name: option-monitor
  labels:
    app: option-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: option-monitor
  template:
    metadata:
      labels:
        app: option-monitor
    spec:
      containers:
        - name: option-monitor
          image: ghcr.io/bestnathan/nq-rs/deribit-option-monitor:sha-8604a48
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: info
            - name: DERIBIT_API_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: option-monitor-secrets
                  key: DERIBIT_CLIENT_ID
            - name: DERIBIT_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: option-monitor-secrets
                  key: DERIBIT_CLIENT_SECRET
            - name: EMQX_HOST
              value: emqx-nodeport.emqx.svc.cluster.local
            - name: ALL_PROXY
              value: http://192.168.2.98:8890
            - name: HTTPS_PROXY
              value: http://192.168.2.98:8890
            - name: DERIBIT_OPTION_CURRENCIES
              value: BTC,ETH
            - name: DERIBIT_OPTION_TICKER_INTERVAL
              value: agg2
            - name: DERIBIT_OPTION_POOL_CAPACITY
              value: "2000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      imagePullSecrets:
        - name: ghcr-bestnathan
      nodeSelector:
        kubernetes.io/arch: amd64
